version: '3'

services:

  git-server:
    image: docker.zivili.ch/gbili/git-server-hooks
    container_name: git-server-hooks
    ports:
      - "2222:22"
    volumes:
      - git-server-keys:/git-server/keys
      - git-server-repos:/git-server/repos
      - node-apps:/git-server/node-app
    restart: always

volumes:
  git-server-keys:
  git-server-repos:
  node-apps: