version: '3.7'

services:
  git-server:
    image: docker.zivili.ch/gbili/git-server-hooks:0.0.4
    container_name: git-server-hooks
    environment:
      VIRTUAL_HOST: <VIRTUAL_HOST>
      LETSENCRYPT_HOST: <VIRTUAL_HOST>
      LETSENCRYPT_EMAIL: mail@<VIRTUAL_HOST>
    ports:
      - "2222:22"
    volumes:
      - git-server-keys:/<GIT_SERVER_DIR>/keys
      - git-server-repos:/<GIT_SERVER_DIR>/<GIT_REPO_OWNERNAME>
      - node-apps:/node-server/<GIT_REPO_OWNERNAME>
    restart: always

volumes:
  git-server-keys:
  git-server-repos:
  node-apps:

# add it to your desired network
# e.g. let's encrypt nginx certbot (created separately)
networks:
  default:
    external:
      name: nginx-proxy